### ISSUE TITLE
Tabs and spaces

### ISSUE THREAD

**Issue by AjaiKN** [ObieSource/obiesource.github.io#17]
We've been inconsistent about tabs vs. spaces, and we should decide which one to use.

**Comment by FiskFan1999** [comment]
I wonder if there is an automatic formatter that can be applied to the html, similar to gofmt for golang.

**Comment by AjaiKN** [comment]
Prettier can format HTML, CSS, JSON, and JavaScript.

**Comment by FiskFan1999** [comment]
I wonder if there is an automatic formatter script. Kind of like gofmt

**Comment by AjaiKN** [comment]
That's exactly what prettier is.

**Comment by AjaiKN** [comment]
We now have prettier set up. It should format on save in VSCode, and we also added a GitHub Action that re-formats the code in the main branch (with an automated commit) if it's not formatted.
