### ISSUE TITLE
list website in repository details

### ISSUE THREAD

**Issue by FiskFan1999** [ObieSource/obiesource.github.io#3]
I think it would be a good idea to specify the URL address of the statically hosted repository (https://obiesource.github.io/) as the website in the repository details, so it's more easily accessible. Am interested in your thoughts on this.

**Comment by AjaiKN** [comment]
I'm guessing this'll pretty uncontroversial, so I just did it. If anyone disagrees, feel free to undo it.

**Comment by FiskFan1999** [comment]
> I'm guessing this'll pretty uncontroversial, so I just did it. If anyone disagrees, feel free to undo it.

Thanks @Aurelius333
